server:
  port: 10010 #网关端口
spring:
  application:
    name: gateway #服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos地址
    #      ephemeral: true
    #        cluster-name: HZ
    #        namespace: 7094422b-94ff-418f-810b-3f99e9beb3cf
    gateway:
      routes: # 网关配置
        - id: user-service #路由ID，自定义，只要唯一即可
          uri: lb://userservice #路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: #路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/user/** #这个是按照路径匹配，只要以/user/开头就符合要求- id: user-service #路由ID，自定义，只要唯一即可
        - id: order-service #路由ID，自定义，只要唯一即可
          uri: lb://orderservice #路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: #路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/order/** #这个是按照路径匹配，只要以/user/开头就符合要求
            - After=2037-01-20T17:42:47.789-07:00[America/Denver]
      default-filters:
        - AddRequestHeader=Truth,Itcast is freaking aowsome! # 添加请求头
